= USING SEBI Venlo Assessment Environment
Pieter van den Hombergh <p.vandenhombergh@fontys.nl>
Version 0.1 2016-11-04

== Intro

The current way of working (as of October 2016) involves a number of steps:

* Preparation
 1. Preparing or updating the live image.
 2. Installing the live image on the sticks: prepare sticks.
 3. Preparing an exam, i.e. creating student repositories and initial checkout.
 4. Inserting individual exams on the sticks for an exam
 session. prime sticks
* taking/executing the exam.
 1. Booting student laptops from the USB sticks.

* Post processing
 1. harvest the exam work and commit the final student work.
 2. move the student repositories to the correction server.
 3. initialize the workbench.

Since the typical usage does not always use all steps, the arrangement
has the most frequent steps first and the less frequent steps later in
this text. In particular, the steps 1 and 2 in preparation only have
to be taken to create the initial image or when an update of the image
(e.g. new NetBeans version) is required. The description below is
based on a set of scripts and favors convention over configuration. In
particular, a specific directory layout is part of the convention, and
all scripts are to be executed from or within the assessment relevant
sub-directory as the working directory, since the scripts will look
for specific named files relative to the working directory.

== Assessment preparation.
An Assessment is composed of one or more projects in as many
sub-directories. The assumptions is made that exam questions or
variants thereof can be reused. Our These projects are placed under
the directory questions. In our practice the assessment related
resources are placed under 45_asssessment like in the case of JAVA1: 

[source,shell]
----
├── builds
└── questions
----

For SEBI, this means that you should check out the relevant part of the repository to a sandbox on the preparation workstation. For me (hom) and java1 that is:

[source,shell]
----
$ mkdir -p $HOME/sebi/java1/trunk/
$ cd $HOME/sebi/java1/trunk/
$ svn co svn+ssh://osirix/fontysvenlo.org/home/modules/java1/svnroot/trunk/45_assessment 
----

Since many of the attributes or properties of the assessments for a
course are the same, the conventions says that the properties are: 

* In a file called default.properties in the builds
  directory. Typically this already is present when you check out as
  shown before. If not, create the file, make sure the content is
  correct and add and commit it to the module repository. 
* Derived from the name of the subdirectory for the specific
  exam. Here the convention is to use the exam data in short ISO-8601
  format, YYYYMMDD as in 20160104 (4th of November 2016) for the date
  this text is created.
* In a file named setup.properties, per assessment date (sub directory).

Both property files have the syntax of java property files, which can
be consumed as shell (bash) source files, or parsed by perl. Because
shell (bash) has the peculiarity of not accepting white space around
the assignment operator, write the config declarations without
these. If you need to add you own properties, prefer names and values
without white space, because white space will cause more harm then
good.

Examples (for JAVA1, excerpt:)
[source,shell]
----
## exam name
module_name=JAVA1
## exam type (java, sql ... )
extension=java
# tutors
tutors=hom,hvd,mon
## if true (1) a netbeans project is generated
is_netbeans_project=1
## module repo, for exports
module_repo=file:///home/modules/java1/svnroot
----

setup.properties for JAVA1 assessment on 20161103 in dir …​/20161103:

[source,shell]
----
# safe number
candidate_count=63
stick_id=137
is_netbeans_project=true
----

[IMPORTANT]
In the current setup, the directory that is used on the preparation
server reflects the names and structure of the stick. This means that
the scripts use a global directory /home/exam and steps below will
DELETE ANY PREVIOUS SETUP OF OTHER ASSESSMENTS.

=== Preparing for one Assessment

To make this all work, add the directory containing all scripts to
your PATH variable,
e.g. `PATH=$PATH:/home/prepareassessment/bin`. 

Preparing for an assessment involves:

* Create an appropriately named sub-directory as in 20161103.
* Inside said directory, copy and adapt the setup.properties file, in
  particular set the is_netbeans_project correctly, and the start
  number and count of the sticks to use. This determines the identity
  of the sticks to be used and therefor repositories and sandboxes to
  be created.
* Add the exam solutions somehow. The convention is to put this
  information in a script file called doexports to be executed as
  normal user with ./doexports. For JAVA assessment this typically
  involves creating a somewhat complete sccript, for DBS and STA
  assessments, the question information is in a file called
  questions.txt and makes this script reusable. Note that the script
  does an svn checkout and does NOT use the local sandbox, to ensure
  that the exam questions as used in the exam are also versioned in
  the repository.
* Execute the ./doexports`, which should result in an examsolution and
  an examproject, the later being the sub-directory containing all the
  information to be placed on the stick and imported into the
  student/stick specific repositories. Before you do the next steps,
  check that the examproject directory is complete on the one hand and
  is exactly what you want published on the stick. You could use the
  tools that students use in the assessment (netbeans, r-studio or
  pgadmin) to verify that. 

* Create the repositories. For that we have a script called
  makerepos.pl which uses the information described previously. The
  output of the script is a bash source text, which is conventionally
  redirected to doit.sh. Rationale is that the shell text is
  potentially destructive and must be executed with elevated (sudo)
  rights. 
 1. Do `makerepos.pl > doit.sh`
 2. Then do `sudo bash doit.sh` and have a little patience, as doit.sh
 will create a repository per stick, import the examproject in each of
 them and then will checkout siad repository in a sandbox per
 candidate on the "Desktop" of each stick. This can take a few
 thousand milliseconds.
3. Create a sym-link in the assessment directory called skel.tgz which
should point to a tar.gz file, which in turn should contain the
initial content of the candidate home directory (/home/exam), such
that personal preferences (NetBeans), links in browsers (e.g. javadoc,
postgressql manual) and desktop (xfce) configuration are set up. This
skeleton does NOT contain anything assessment specific. 
4. With stampdesktop you invoke a script that creates a wallpaper per
stick, containing the id of the stick and date of the assessment
(e.g. 2016-11-03). You must run this script with elevated rights, so

[source,shell]
----
$ sudo -s
# stampdesktop
.... some output
# exit
$
----
Stamping the desktop in this way make the desktop recognizable and identifies the stick at the same time.

You are now set up to create the sticks.

=== Stick filling.

The final step before the exam is putting the stick specific content on the sticks.

This step should be executed in the assessment builds sub-directory such as `…​/builds/20161103.`

The script to execute is `primeSticks` , which takes no arguments and
must be executed with elevated privileges, because it copies files and
changes ownership to the exam user (on the stick as well as on the
preparation workstation).

Easiest is to walk to the directory if you are not already there, then
sudo -s, to elevate the rights. Then insert, *calmly*, the sticks into
the USB-hubs. Each hub supports 7 sticks and you can prime the sticks
in batches of 21 max. After all sticks are inserted and all leds on
the hubs are lit, enter the primeSticks command and wait until the
(red) prompt returns. 

We need to stress *insert calmly* because the OS on the preparation
workstation needs some time to detect and recognize the stick and
its ID.

The number-order in which you insert the sticks is irrelevant, but
take care that you insert only sticks that are within the range you
declared in setup.properties., because only those will have a repo and
sandbox prepared.

Example run:
[source,shell]
----
$ sudo -s
# primeSticks
.... output ....
# # do this as often as you have batches of say 21 or have primed all sticks.
# exit
$
----

It proved to be practical to use a random sample stick from the ones
of the first batch to boot the test laptop, to see if indeed all that
is needed, and no more, is on the sample stick. If not, revisit the
previous steps. If that is okay, continue for the remaining batches.

Once you have primed all sticks, you are ready to rock.

[NOTE]
During exam you must somehow register which student got which
stick. This association can be done quite efficiently by making sure
each student has some paper or ID with his student-id in bar-code
format. We use peerweb table cards for that, which are produced by
clicking the appropriate link in the peerweb grouplist view. Put them
on the tables to assign the students to tables and have them come
forward you want the student with this paper, so you can scan it with
a barcode reader. Now the trick is to hand out the sticks in numerical
(or reversed) order and scan into a spreadsheet, in which the first
column holds the sequence numbers of the sticks you are going to use
and next will be the student number. Save it in a file sticks.csv and
commit it to the build too. Format of the csv file: 
[source,shell]
----
sticknr;snummer
100;2224053
101;2524392
102;2632683
----

[TIP]
----
To be on the safe side, and because of the warning before, make a
(tar) backup of both the repositories under /home/exam named
EXAMxyz-repo and all sandboxes under
/home/exam/Desktop/examproject-EXAMxyz. Convention: name the tar files
after the exam, e.g JAVA120161103-repo.tgz and
JAVA120161103-sandboxes.tgz
----

=== Harvesting Work.

Harvesting the work from the sticks uses one script, to be executed
from the assessment relevant build directory. The script
`harvestSticks` reverses the steps of priming the sticks: It copies
the sandbox and reposity from the stick back to their location on the
preparation workstation.

[TIP]
You may have to restore the repositories and sandboxes your saved
previously. You may also want to consult the colleague that left any
assessment repos lying and or sandboxes around. Maybe it is time to
save them.


Elevate your rights, insert all sticks that have been used in batches and per batch execute `harvestSticks`.

Example:
[source,shell]
----
$ sudo -s
# harvestSticks # may have to do multiple times in batches

....output omitted....
# exit
$
----
=== Prepare for Correction

We use the *corrector’s workbench* to correct the students work. Preparing this requires a few steps, some of them on the preparation workstation, some on the correction server, _osirix_.

==== Make the last commit and backup.
On the Preparation workstation do the following:

1. elevate your rights.
2. login as exam user (su -l exam)
3. directory-walk to the exam-user’s Desktop and for all repositories,
do an `svn update` per repository and then a final harvesting `svn
commit` per repository. This will ensure that all work is in the
repositories.
4. Make a tar of both the repos and the sandboxes.
5. secure copy the tars to you home dir on the correction server (osirix). 

==== Init the corrector’s work bench.

The corrector’s work bench uses a set of scripts and a database and
php and html to create the UI. This needs to be configured per
assessment.

1. Log in to the correction server.
2. Check out or update the 45_assessment directory for the exam and
walk to the directory for the specific date. Maybe mv the earlier
scpied tar files here too.
3. execute the scripts filldbquestions 4.

sticks.csv contents.

filldb

connectsticks.

web server restart

