#!/bin/bash
# steps: 
# 1. enumerated inserted sticks using /proc/mounts and regex
# 2. unmount them all
# 3. write partition table
# 4. create vfat and ext3 file system
# 4. label vfat to name stick, e.g. EXAM100 and ext3 part to casper-rw
# 5. syslinux --install  /dev/sd?1
# 6. mount vfat part to /media/hom/STICK-ID
# 7. cp -r /home/ISO/. /media/hom/STICK-ID
if [ -z $STICK_CLASS ] ; then
    export STICK_CLASS=EXAM
fi
scriptdir=$(dirname $(readlink -f $0))
ininum=100
if [ $# -ge 1 ]; then ininum=$1; shift; fi 
parttable=part-16GB
disks=''
for d in $(cat /proc/mounts  | grep -P '\/dev\/sd[cdefghijklmnop]1' | cut -d ' ' -f1  ) ; do
    if [ ${disks}a == 'a' ]; then disks="$d"; else disks="$disks,$d"; fi
done
echo $disks
IFS=','
debug=

partitionStick(){
    local parttablefile=${scriptdir}/part-16GB
    disk=$1
    if [ $(sfdisk -s ${disk}) -gt 16000000 ] ; then 
	echo using 32G partition on device ${disk}
	parttablefile=${scriptdir}/part-32GB
    fi
    cat ${parttablefile} | sfdisk -q --force $disk >> sfdisk.log
}

prepaperStick() {
    local d=$1
    local LABEL=$2
    ${debug} umount -d ${d/1/}2
    ${debug} umount -d ${d}
    ${debug} partitionStick ${d/1/}
    ${debug} mkfs.vfat -n ${LABEL} ${d}
    ${debug} mkfs.ext2 -q -L home-rw ${d/1/2}
    echo done creating ext2 part on ${d/1/2}
#    ${debug} mlabel -i ${d} ::$LABEL
#    ${debug} e2label ${d/1/2} casper-rw
}

installToStick() {
    local d=$1
    local LABEL=$2
    local MOUNTPOINT=/media/usb/${LABEL}
    ${debug} mkdir -p ${MOUNTPOINT}
    ${debug} mount ${d}  ${MOUNTPOINT}
    echo  start copy of ISO files to stick ${LABEL}
    ${debug} cp -r /home/ISO/{boot,casper,.disk,dists,EFI,install,md5sum.txt,pics,pool,preseed,README.diskdefines} ${MOUNTPOINT}
    ${debug} cp -r /home/ISO/isolinux ${MOUNTPOINT}/syslinux
    echo  rename syslinux.cfg for stick ${LABEL}
    ${debug} mv ${MOUNTPOINT}/syslinux/{iso,sys}linux.cfg
    echo creating casper-rw file space for stick ${LABEL}
    ${debug} dd if=/dev/zero of=${MOUNTPOINT}/casper-rw bs=1M count=1024
    echo creating casper-rw file system for stick ${LABEL}
    mkfs.ext3 -q -F ${MOUNTPOINT}/casper-rw
#    ${debug} syslinux --install ${d}
    ${debug} syslinux --stupid ${d}
    echo installation for stick ${LABEL} done
}

num=${ininum}
for d in $disks; do 
    umount ${d} ${d/1/2}
    num=$((num+1))
done
sync

num=${ininum}
for d in $disks; do 
    printf -v LABEL "${STICK_CLASS}%3.3d" $((${EXAMBASE}+${num}))
     ( prepaperStick ${d} ${LABEL} )& 
    num=$((num+1))
done

wait
echo done partioning sticks $disks
# sync
# num=${ininum}
# for d in $disks; do 
#     printf -v LABEL "${STICK_CLASS}%3.3d" $((${EXAMBASE}+${num}))
#      ( installToStick ${d} ${LABEL} )& 
#     num=$((num+1))
# done

# wait
# sync
# for d in $disks; do 
#     echo done with stick ${d}
#     ${debug} umount -d ${d}
# done
echo next num=${num}
rm -fr /media/usb
paplay ${scriptdir}/programisready.ogg
