#!/bin/bash
eval $(confparams)
rm -fr ${webdir}/harvest/sandbox
harvester ${svn_root}

# echo continue work in ${webdir}
# cd ${webdir}
flag='editor-fold'
extension='R'
echo snipping exam
for f in $(grep -rl ${flag} ${webdir}/harvest/sandbox/); do
    echo ${f} 
    cat $f | snipper ${f##*.}
done

echo snipping solution
for f in $(grep -rl __STUDENT_ID__ examsolution); do
    cat $f | snipper-sol  ${f##*.}
done
 
for i in $(find ${webdir}/harvest -name "*.R.snippet"); do 
    ( enscript --line-numbers -whtml -Esh -q  --color -p -  $i | stripsnip.pl > $i.html &); 
done

# run complete files in workdir
if [[ $extension == 'R' ]] ; then
    for i in $(find ${webdir}/harvest -name "*.R"); do 
	( 
	    enscript --line-numbers -whtml -Esh -q  --color -p -  $i | stripsnip.pl > $i.html 
	    cd $(dirname ${i}) 
	    echo appending  r run to  ${i}.html
	    outfile=$(basename ${i} .R).out
	    echo -n > ${outfile}
	    cat  $i | grep -v '^#' | R --silent --no-save ${i} &>> ${outfile}
	    echo "<pre style='color:#008'>" >> ${i}.html
	    cat  ${outfile} >> ${i}.html  
	    echo "<pre>" >> ${i}.html
	    if [ -f Rplots.pdf ]; then
		for p in *.pdf; do
		    convert $p $(basename $p .pdf).png
		done
	    fi
	) 
    done
fi

# for i in $(find ${webdir}/harvest -name "*.${extension}"); do
#     ( enscript --line-numbers -whtml -Esh -q  --color -p -  $i | stripsnip.pl > $i.html &); 
# done

# link to resources
filldb.pl

